/**
 * أطلس الواحة الحضرية: صفحات الدليل تعتمد على تسلسل قرائي واضح وجداول عملية قابلة للمراجعة.
 */
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowUpLeft, Check, ChevronDown, CircleAlert, ExternalLink, Gauge, MapPin, Route, SlidersHorizontal, TrainFront } from "lucide-react";
import SEO from "@/components/SEO";
import SiteLayout, { RouteBadge } from "@/components/SiteLayout";
import PageHero from "@/components/PageHero";
import { developers, faqs, neighborhoods, references } from "@/lib/guide-data";

const SupportLinks = ({ items }: { items: [string, string][] }) => <div className="related-links">{items.map(([href, label]) => <Link key={href} href={href}><ArrowUpLeft size={15} /> {label}</Link>)}</div>;
const SourceList = () => <section className="sources-box"><p>مصادر للقراءة والتحقق</p><ol>{references.map((r, i) => <li key={r.href}><a href={r.href} target="_blank" rel="noreferrer">[{i + 1}] {r.label} <ExternalLink size={12} /></a></li>)}</ol></section>;

export function AboutPage() {
  return <SiteLayout><SEO title="عن مدينة العبور الجديدة" description="نبذة محايدة عن مدينة العبور الجديدة، المساحة والموقع وعلاقتها بمدينة العبور القائمة." schema={{ "@context": "https://schema.org", "@type": "Place", name: "مدينة العبور الجديدة", description: "مدينة جديدة في محافظة القليوبية، مصر." }} />
    <PageHero eyebrow="بطاقة المدينة" title="العبور الجديدة: مخطط جديد لا امتداد تلقائي" description="قراءة عملية للموقع، مساحة التخطيط، وما الذي يجب أن تميّزه عن مدينة العبور القائمة عند مقارنة السكن أو الاستثمار." tag="عن المدينة" />
    <section className="section-shell paper-section"><div className="container content-grid"><article className="prose-card"><h2>مدينة جيل جديد بمراحل مختلفة</h2><p>أُنشئت العبور الجديدة بقرار جمهوري سنة 2016 وتتبع منظومة هيئة المجتمعات العمرانية الجديدة. تشير بيانات التخطيط المنشورة إلى مساحة إجمالية تقترب من 59 ألف فدان، مع كتلة عمرانية تقارب 22 ألف فدان.[1]</p><p>هذه الأرقام لا تعني أن كل جزء داخل الحدود في المرحلة نفسها. توجد أحياء ذات سكن وخدمات أكثر نضجًا، وأخرى ما زالت تمثل توسعًا أو طروحات مرتبطة بجدول تنفيذ. لذلك لا ينبغي اختصار المدينة في «سعر متر» واحد أو وصف عام.</p><h3>الفرق الذي يهم المشتري</h3><div className="comparison-grid"><div><span>العبور القائمة</span><b>مدينة أقدم غرب النطاق</b><p>خدمات وحياة يومية أكثر استقرارًا في نطاقات متعددة، مع تباين قوي بين الشوارع والمناطق.</p></div><div><span>العبور الجديدة</span><b>تخطيط أحدث وامتدادات أوسع</b><p>فرص شراء على مراحل، مع حاجة أكبر لفحص البنية التحتية وتوقيت الخدمات في كل منطقة.</p></div></div></article><aside className="fact-rail"><RouteBadge>علامات الخريطة</RouteBadge><div><b>شمالًا</b><span>طريق القاهرة–بلبيس الصحراوي</span></div><div><b>جنوبًا</b><span>طريق القاهرة–الإسماعيلية الصحراوي</span></div><div><b>غربًا</b><span>مدينة العبور القائمة</span></div><div><b>شرقًا</b><span>اتجاه العاشر من رمضان</span></div></aside></div></section>
    <section className="section-shell"><div className="container"><h2 className="section-title">لماذا يتابعها الباحثون عن السكن؟</h2><div className="principle-grid"><div><MapPin /><b>موقع بين محاور</b><p>القيمة العملية تختلف حسب طريقك اليومي لا حسب القرب على الخريطة وحده.</p></div><div><Route /><b>احتياطي توسع</b><p>المدينة ذات نطاق تخطيطي واسع، لكن التطوير الفعلي يحتاج قراءة مرحلة بمرحلة.</p></div><div><TrainFront /><b>ربط جماعي</b><p>وجود مسار LRT عنصر وصول مهم، وتبقى محطة الانطلاق والمسافة منها جزءًا من المقارنة.</p></div></div><SupportLinks items={[["/transport", "مسار الوصول والمواصلات"], ["/districts", "كيف تختار الحي؟"], ["/buying-guide", "قائمة فحص قبل الشراء"]]} /></div></section><SourceList />
  </SiteLayout>;
}

export function DistrictsPage() {
  return <SiteLayout><SEO title="الأحياء والمناطق" description="دليل مبسط لأحياء ومناطق مدينة العبور الجديدة، مع طبيعة كل نطاق ومن يناسبه." schema={neighborhoods.map((n) => ({ "@context": "https://schema.org", "@type": "Place", name: n.title, description: n.note }))} />
    <PageHero eyebrow="خريطة الاختيار" title="الأحياء لا تُقارن بالاسم فقط" description="استخدم المرحلة، قرب الخدمات، ونوع هدفك للوصول إلى قائمة معاينات قصيرة بدل الاعتماد على وصف تسويقي عام." tag="الأحياء والمناطق" />
    <section className="section-shell green-section"><div className="container"><p className="eyebrow text-[#A9D6CD]">مصفوفة قرار سريعة</p><div className="district-grid">{neighborhoods.map((n) => <article key={n.title} className="district-card"><span className="district-code">{n.code}</span><p className="district-status">{n.status}</p><h2>{n.title}</h2><p>{n.note}</p><div><b>مناسب لـ</b><span>{n.fit}</span></div></article>)}</div></div></section>
    <section className="section-shell paper-section"><div className="container content-grid"><article className="prose-card"><h2>ما الذي تسأل عنه عند معاينة الحي؟</h2><p>ابدأ من هدفك الزمني. من ينتقل خلال أشهر يحتاج اختبار الخدمة الفعلية: الرصف، الإضاءة، المياه، المدارس، ومحلات اليوم العادي. أما المشتري المبكر فيقارن أيضًا مخطط المحاور، التخصيص، ومسار المرافق المتوقع.</p><div className="check-list">{["الموقع الفعلي للقطعة أو المشروع لا مجرد اسم الحي.", "وقت الوصول في رحلة حقيقية وليس بتقدير تسويقي.", "حالة المرافق في الشارع المحيط لا عند البوابة فقط.", "نوع الاستخدامات المجاورة وخطتها المعلنة.", "مرحلة التنفيذ وموعد الخدمات المكتوب إن وجد."].map((x) => <p key={x}><Check size={17} />{x}</p>)}</div></article><aside className="action-rail"><p>تحتاج قراءة الأسعار؟</p><Link href="/prices" className="primary-cta">افتح لقطة السوق <ArrowUpLeft size={16} /></Link><Link href="/transport" className="text-link">اربط الحي بمسارك اليومي <ArrowUpLeft size={15} /></Link></aside></div></section><SourceList />
  </SiteLayout>;
}

export function TransportPage() {
  return <SiteLayout><SEO title="المواصلات والوصول" description="دليل الوصول إلى مدينة العبور الجديدة: القطار الكهربائي الخفيف LRT والمحاور وقراءة مسافة الرحلة." schema={{ "@context": "https://schema.org", "@type": "ItemList", name: "محاور الوصول إلى العبور الجديدة", itemListElement: ["محطة العبور LRT", "الدائري الأوسطي", "محور R2"] }} />
    <PageHero eyebrow="المدينة في حركة" title="الوصول يبدأ من مسارك اليومي" description="القرب من المحور لا يكفي وحده؛ قارن محطة البداية، زمن الذروة، ونقطة النزول لتفهم قيمة الموقع في حياتك اليومية." tag="المواصلات والوصول" />
    <section className="section-shell paper-section"><div className="container content-grid"><article className="prose-card"><h2>القطار الكهربائي الخفيف LRT</h2><p>يربط مسار LRT عدلي منصور بعدة مدن جديدة، ويشمل محطة العبور ضمن المحطات المعلنة. وتوضح بيانات تنفيذ منشورة أن المسار الأساسي يخدم العبور والمستقبل والشروق وبدر والعاصمة الإدارية والعاشر من رمضان، بسرعات تشغيل تصل إلى 120 كم/ساعة في مكوناته.[2][3]</p><p>للقرار السكني، لا تتعامل مع المحطة كضمان مستقل: قِس زمن انتقالك من الوحدة إلى المحطة ومن المحطة إلى وجهتك، واسأل عن وسيلة الربط الأخيرة وتكلفتها.</p><div className="transport-stat"><TrainFront /><div><strong>محطة العبور</strong><span>ضمن مسار الربط بين عدلي منصور والمدن الشرقية</span></div></div></article><aside className="fact-rail"><div><b>الدائري الأوسطي</b><span>عامل وصول مهم للمناطق القريبة، ويُقاس بزمن الرحلة الفعلي.</span></div><div><b>محور R2</b><span>يرتبط بمناطق طرح وتوسع مثل أجزاء من الحي 24.</span></div><div><b>المطار والعاصمة</b><span>لا تكتفِ بالمسافة؛ راجع نقطة الدخول والزحام وساعات الحركة.</span></div></aside></div></section>
    <section className="section-shell"><div className="container"><div className="distance-table"><div className="distance-head"><span>الوجهة</span><span>كيف تقرأ العلاقة؟</span><span>اختبر ميدانيًا</span></div>{[["مدينتي / التجمع", "اتصال عبر المحاور الشرقية", "وقت الذروة ومسار الدخول"], ["الشروق", "قرب نسبي من امتداد المدن الجديدة", "الطريق ونقطة الإنزال"], ["العاصمة الإدارية", "ربط طريق وقطار حسب نقطة البداية", "المسافة إلى محطة LRT"], ["المطار", "يتغير حسب المحور ووقت الرحلة", "الذهاب والعودة في ساعات العمل"]].map((row) => <div className="distance-row" key={row[0]}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div><SupportLinks items={[["/districts", "حدّد الحي قبل قياس الرحلة"], ["/about", "بطاقة موقع المدينة"], ["/faq", "أسئلة شائعة عن الوصول"]]} /></div></section><SourceList />
  </SiteLayout>;
}

export function PricesPage() {
  return <SiteLayout><SEO title="أسعار العقارات" description="لقطة استرشادية لأسعار العقارات في مدينة العبور الجديدة وطريقة استخدامها دون مبالغة." />
    <PageHero eyebrow="لقطة سعرية مؤرخة" title="السعر مؤشر، لا بديل عن المقارنة" description="نستخدم المتوسطات لتحديد نطاق البحث فقط. أما السعر الحقيقي فيتغير حسب المرحلة والموقع ونظام السداد وحالة التنفيذ." tag="أسعار العقارات" />
    <section className="section-shell paper-section"><div className="container grid gap-9 lg:grid-cols-[.9fr_1.1fr] items-center"><div className="price-signal"><p>لقطة كمبوندات · مايو 2026</p><strong>32,900 <small>جنيه / م²</small></strong><span>متوسط إرشادي مذكور في موجز العمل، وليس تسعيرًا ملزمًا لأي مشروع.</span></div><article className="prose-card"><h2>كيف تستخدم هذا الرقم بشكل صحيح؟</h2><p>المتوسط لا يساوي تقييم المشروع. قد تزيد أو تنخفض القيمة مع الموقع الدقيق، مستوى التشطيب، إجمالي الدفعات، مساحة الوحدة، نسبة الإنشاء، ومصداقية موعد التسليم. لا تقارن سعرًا نقديًا بسعر تقسيط دون حساب التكلفة الإجمالية.</p><div className="note-box"><CircleAlert size={19}/><span>نسبة الارتفاع السنوي (27.57%) المذكورة في موجز المشروع تستخدم كبيان تاريخي مؤرخ، وليست توقعًا أو توصية استثمارية. راجع مصدره وتاريخ القياس قبل الاعتماد عليه.</span></div></article></div></section>
    <section className="section-shell"><div className="container"><h2 className="section-title">جدول نطاقات استرشادية للمقارنة</h2><div className="price-table"><div className="price-table-head"><span>نوع البحث</span><span>ما الذي يغيّر السعر؟</span><span>سؤال المقارنة</span></div>{[["وحدة في حي قائم", "الحالة والتشطيب والخدمات", "ما تكلفة الانتقال الفعلية؟"], ["كمبوند تحت التنفيذ", "موعد التسليم والسداد والكثافة", "هل السعر يشمل كل الرسوم؟"], ["أرض أو طرح مبكر", "التخصيص والمرافق وزمن التطوير", "ما الخطوة التالية المكتوبة؟"], ["مقارنة مع التجمع / العاصمة", "القرب من العمل وبدائل النقل", "كم تدفع لكل دقيقة وصول؟"]].map((row) => <div className="price-row" key={row[0]}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div><SupportLinks items={[["/developers", "افحص المطور قبل مقارنة السعر"], ["/districts", "اربط السعر بمرحلة الحي"], ["/buying-guide", "احسب التكلفة الكلية"]]} /></div></section><SourceList />
  </SiteLayout>;
}

const labels: Record<keyof typeof developers[0], string> = { name: "", delivered: "التسليم", management: "الإدارة", finance: "الملاءة", transparency: "الشفافية", density: "الكثافة", evidence: "", source: "", featured: "" };
export function DevelopersPage() {
  const [sort, setSort] = useState<"total" | "delivered" | "management" | "finance" | "transparency" | "density">("total");
  const ordered = useMemo(() => [...developers].sort((a, b) => { const score = (d: typeof developers[number]) => sort === "total" ? d.delivered + d.management + d.finance + d.transparency + d.density : d[sort]; return score(b) - score(a); }), [sort]);
  const developerSchema = { "@context": "https://schema.org", "@type": "ItemList", name: "دليل مطوري العبور الجديدة", itemListElement: developers.map((d, index) => ({ "@type": "ListItem", position: index + 1, name: d.name })) };
  return <SiteLayout><SEO title="دليل المطورين" description="مقارنة موضوعية قابلة للفرز لمطوري العبور الجديدة على خمسة معايير معلنة وقابلة للتحقق." schema={developerSchema} />
    <PageHero eyebrow="المقارنة الأهم" title="دليل المطورين: الدليل قبل الدرجة" description="لا تُفرض النتيجة على البيانات. نقيّم ما هو منشور وقابل للفحص، ونذكر حدود المعلومات المتاحة بوضوح." tag="دليل المطورين" />
    <section className="section-shell paper-section"><div className="container"><div className="criteria-grid">{[["01", "سابقة الأعمال المسلّمة", "وحدات قائمة يمكن زيارتها"], ["02", "إدارة ما بعد التسليم", "جهة إدارة وخبرة تشغيل محددة"], ["03", "الملاءة المالية", "شراكات أو تمويل معلن قابل للتحقق"], ["04", "شفافية التعاقد", "مواصفات وتكاليف مكتوبة"], ["05", "البناء والكثافة", "النسبة والارتفاعات وجودة المساحات"]].map(([n, title, note]) => <div key={n}><span>{n}</span><b>{title}</b><p>{note}</p></div>)}</div></div></section>
    <section className="section-shell"><div className="container"><div className="sort-toolbar"><div><p className="eyebrow">جدول تفاعلي</p><h2 className="section-title mb-0">رتّب وفق المعيار الذي يهمك</h2></div><label><SlidersHorizontal size={17}/><span className="sr-only">الترتيب</span><select value={sort} onChange={(e) => setSort(e.target.value as typeof sort)}><option value="total">المجموع الكلي</option>{(["delivered", "management", "finance", "transparency", "density"] as const).map((key) => <option key={key} value={key}>{labels[key]}</option>)}</select></label></div>
        <div className="developer-table-wrap"><table className="developer-table"><thead><tr><th>المطور</th><th>تسليم</th><th>إدارة</th><th>ملاءة</th><th>شفافية</th><th>كثافة</th><th>المجموع</th></tr></thead><tbody>{ordered.map((dev) => { const total = ((dev.delivered + dev.management + dev.finance + dev.transparency + dev.density) / 5).toFixed(1); return <tr key={dev.name} className={dev.featured ? "featured-row" : ""}><td><b>{dev.name}</b><small>{dev.source}</small></td>{(["delivered", "management", "finance", "transparency", "density"] as const).map((key) => <td key={key}><span className="score-cell">{dev[key]}</span></td>)}<td><strong>{total}<small>/5</small></strong></td></tr>; })}</tbody></table></div>
        <p className="table-caption">الدرجة من 5 إرشادية ومبنية على البيانات المنشورة المتاحة وقت التحديث. «قيد الاستكمال» ليست درجة سلبية؛ تعني أن الدليل العلني غير كافٍ للمقارنة الدقيقة.</p>
      </div></section>
    <section className="section-shell olive-spotlight"><div className="container grid gap-9 lg:grid-cols-[1.1fr_.9fr]"><article><RouteBadge>كيف تقيّم أي مطوّر</RouteBadge><h2>لا تبدأ من الاسم التجاري</h2><p>الدرجة في الجدول تقيس حجم ما ينشره المطور وتستطيع التحقق منه بنفسك، لا جودة الشركة المطلقة. شركة كبيرة لا تنشر بياناتها تحصل على درجة منخفضة هنا، وهذا مقصود. لذلك لا تعتمد على اللقب أو الإعلان؛ ابدأ بالوحدات القابلة للزيارة، وجهة الإدارة بعد التسليم، التمويل المعلن، العقد النموذجي، والنسبة والارتفاعات.</p><p>اطلب من أي مطور — سواء كان من الجدول الرئيسي أو قيد الاستكمال — الأدلة نفسها: وحدات مسلّمة يمكن معاينتها، اسم جهة إدارة مرافق مع سجل تشغيل، شراكة تمويل قابلة للتحقق، مواصفات تشطيب مكتوبة، ونسبة بناء معتمدة. ما لا يستطيع تقديمه يبقى نقصًا يجب أخذه في الحسبان.</p><Link href="/buying-guide" className="primary-cta mt-6 inline-flex">اقرأ دليل الشراء خطوة بخطوة <ArrowUpLeft size={17} /></Link></article><aside className="evidence-panel"><p>ما الذي يمكن فحصه؟</p>{["زيارة مشروع قائم وحالته التشغيلية", "اسم جهة الإدارة وميزانية الصيانة", "شراكة التمويل ومستنداتها", "ملحق المواصفات والتكلفة", "نسبة البناء والمخطط المعتمد"].map((x) => <span key={x}><Check size={16}/>{x}</span>)}</aside></div></section><SourceList />
  </SiteLayout>;
}

export function BuyingGuidePage() {
  return <SiteLayout><SEO title="دليل الشراء" description="خطوات عملية لشراء وحدة في العبور الجديدة، من تحديد الهدف إلى فحص الأرض والعقد." />
    <PageHero eyebrow="قرار قابل للتدقيق" title="دليل شراء هادئ: من الهدف إلى العقد" description="رتّب القرار في خطوات. لا يدفعك عرض سعر أو موعد محدود لتجاوز فحص الموقع والوثائق." tag="دليل الشراء" />
    <section className="section-shell paper-section"><div className="container"><div className="buying-path">{[["01", "حدد الهدف والزمن", "سكن قريب أم استثمار بأفق أطول؟ هذا يحدد الحي ونوع الوحدة."], ["02", "اختصر المواقع", "قارن 3 خيارات متشابهة بدل عشرات الإعلانات غير المتجانسة."], ["03", "عاين في وقتين", "زر في يوم عمل وفي وقت ذروة لتفهم الطريق والخدمات."], ["04", "راجع الأرض والترخيص", "اطلب تخصيص الأرض والترخيص والمخطط والالتزامات المكتوبة."], ["05", "اقرأ العقد كتكلفة كلية", "السعر، الصيانة، التسليم، الغرامات، والتشطيب يجب أن تكون واضحة."], ["06", "احتفظ بمقارنة مكتوبة", "التوثيق البسيط يحميك من القرار العاطفي أو ضغط المبيعات."]].map(([n,title,text]) => <div key={n}><span>{n}</span><h2>{title}</h2><p>{text}</p></div>)}</div></div></section>
    <section className="section-shell"><div className="container content-grid"><article className="prose-card"><h2>الأسئلة الخمسة لأي مطور</h2><div className="check-list">{[["السابقة", "أين مشروع مسلّم يمكن زيارته؟"], ["الإدارة", "من يدير المكان بعد التسليم؟"], ["التمويل", "ما أساس تمويل التنفيذ؟"], ["العقد", "ما المواصفات والتكاليف المكتوبة؟"], ["الكثافة", "ما نسبة البناء والارتفاعات؟"]].map(([a,b]) => <p key={a}><Gauge size={17}/><span><b>{a}: </b>{b}</span></p>)}</div><Link href="/methodology" className="text-link">منهجية التقييم الخمسة <ArrowUpLeft size={15}/></Link></article><aside className="action-rail"><p>قارن قبل أن تلتزم</p><Link href="/developers" className="primary-cta">قارن المطورين <ArrowUpLeft size={16}/></Link><Link href="/prices" className="text-link">افتح دليل قراءة الأسعار <ArrowUpLeft size={15}/></Link></aside></div></section><SourceList />
  </SiteLayout>;
}

export function FAQPage() {
  const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) };
  const [open, setOpen] = useState(0);
  return <SiteLayout><SEO title="الأسئلة الشائعة" description="إجابات مباشرة على أسئلة السكن والاستثمار والمواصلات والأسعار في مدينة العبور الجديدة." schema={schema} />
    <PageHero eyebrow="إجابات قابلة للاقتباس" title="أسئلة شائعة عن العبور الجديدة" description="إجابات مختصرة تشرح الصورة دون أن تتجاوز حدود ما يمكن التحقق منه. ارجع للمصدر أو للزيارة الميدانية في القرار النهائي." tag="الأسئلة الشائعة" />
    <section className="section-shell paper-section"><div className="container max-w-4xl"><div className="faq-list">{faqs.map(([q, a], index) => <article key={q} className={`faq-item ${open === index ? "faq-open" : ""}`}><button onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span>{q}</span><ChevronDown size={20}/></button><div className="faq-answer"><p>{a}</p></div></article>)}</div><SupportLinks items={[["/developers", "كيف نقارن المطورين؟"], ["/transport", "دليل المواصلات"], ["/buying-guide", "خطوات الشراء"]]} /></div></section><SourceList />
  </SiteLayout>;
}
